# Debug Dockerfile to test Java installation step by step
FROM apache/airflow:3.0.2 as base

USER root
RUN apt-get update

FROM base as java-test
RUN apt-get install -y default-jdk
RUN java -version

FROM java-test as maven-test  
RUN apt-get install -y maven
RUN mvn -version

FROM maven-test as final
USER airflow
RUN pip install --no-cache-dir py4j jaydebeapi
